version: "3.7"

services:
    # image project
    app:
        container_name: app-laravel
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        networks:
            - laravel
        command: sh -c "composer install && php artisan scribe:generate && php -S 0.0.0.0:8000 -t public"
    # db mysql
    db:
        container_name: app-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - /docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
